### ISSUE TITLE
Allow for a custom node store to be passed in

### ISSUE THREAD

**Issue by justinedelson** [adamcin/oakpal#14]
It would be helpful if there was a way to pass in a custom node store to OakMachine. This would be helpful, for example, when trying out different blob storage scenarios.

**Comment by adamcin** [comment]
@justinedelson I merged the PR and then made changes to reflect my comments in d3636aa8c1fa354676bf20fadd8b7a79b2cb65fe .

**Comment by justinedelson** [comment]
I'm fully onboard with your changes :) thanks for fixing my dashed off code
