### ISSUE TITLE
Update to Oak 1.8.4 (or higher)

### ISSUE THREAD

**Issue by justinedelson** [adamcin/oakpal#3]
In addressing https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1619, I found that oakpal uses Oak 1.7.14. I worked around it by forcing the version to be 1.8.9 (https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1621/files#diff-8ec6b959c735e6d2d5873b5c27e76169R103) but it would probably be a good idea for oakpal to use a version of Oak higher than 1.8.4 to get the fix from https://issues.apache.org/jira/browse/OAK-7186.

**Comment by adamcin** [comment]
Okay, I'll make that change.

**Comment by justinedelson** [comment]
Also, I'm pretty sure that odd minor numbers are "unstable" releases in Oak, so moving to 1.8.x is probably a good idea regardless.

**Comment by adamcin** [comment]
Thanks, I'll make a note of that in the pom.
