### ISSUE TITLE
Maven plugin reports "Failed to find node type definition"

### ISSUE THREAD

**Issue by gruberrolandvaltech** [adamcin/oakpal#34]
Hi, 

we get this error when running the scan:

Failed to execute package scan. Failed to resolve cndNames.: Failed to find node type definition on classpath for cndName FILE.

FILE is the absolute path to the downloaded node types from AEM. Any clue what could cause this issue? We use 1.5.1.

			<plugin>
				<groupId>net.adamcin.oakpal</groupId>
				<artifactId>oakpal-maven-plugin</artifactId>
				<configuration>
 					<cndNames>
						<cndName>${project.basedir}/src/test/resources/exportnodetype.jsp</cndName>
					</cndNames>
					<checklists>
						<checklist>basic</checklist>
					</checklists>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>scan</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

**Comment by adamcin** [comment]
Hi @gruberrolandvaltech, the `<cndNames>` parameter references files on the project's `test`-scope classpath, so you should remove the `${project.basedir}/src/test/resources/` prefix to leave only `exportnodetype.jsp`, as this file should be copied to `${project.build.testOutputDirectory}` by the maven-resources-plugin before the `integration-test` phase.

**Comment by gruberrolandvaltech** [comment]
Thanks a lot for your fast reply! This helped. :smile: :thumbsup:
