### ISSUE TITLE
Documentation issue on installHookPolicy

### ISSUE THREAD

**Issue by gruberrolandvaltech** [adamcin/oakpal#35]
Just a small issue: the docs say that hooks are skipped by default but default seems to be "REPORT":
https://github.com/adamcin/oakpal/blob/master/core/src/main/java/net/adamcin/oakpal/core/InstallHookPolicy.java

I had to set this to SKIP in 1.5.1 to avoid issues with not found hook classes.

It would be great if the possible values are documented here: http://adamcin.net/oakpal/oakpal-maven-plugin/scan-mojo.html

**Comment by adamcin** [comment]
Thanks for identifying this!
