### ISSUE TITLE
Gradle usages

### ISSUE THREAD

**Issue by pun-ky** [adamcin/oakpal#36]
First of all, thanks for great tool. Looks very promising.

I'd like to use it in Gradle build.

1. Could you provide minimal snippet (e.g in Java) to use static package analysis for built CRX packages? So that I could be able to use that snippet while implementing Gradle task?
2. Could you consider implementing also Gradle plugin with options similar to Maven plugin?

**Comment by pun-ky** [comment]
https://github.com/adamcin/oakpal/blob/master/maven/src/main/java/net/adamcin/oakpal/maven/mojo/AbstractITestWithPlanMojo.java#L377-L410

**Comment by pun-ky** [comment]
![image](https://user-images.githubusercontent.com/10673561/67838826-857b7100-faf2-11e9-988f-c3659d86b2fe.png)

@adamcin few things about Docker/CLI

1. I completely don't know if Opear that I want to use is actually in use; CLI should write line sth like "Using Opear file: xxxx.jar"
2. I don't know how to specify plan to CLI... should it have *.json* in the end? I also don't know if plan could be provided outside Opear.. as in my case.

My goal is to validate my package built by Gradle AEM Plugin and in the end run OakPal with checklists coming from ACS AEM Commons and Basic from OakPAL (of course if it seems logic ;)).

Seems that ACS AEM Commons Opear file does not provide any plans... so how to provide it externally? Is rebuilding whole Opear needed in that case / only way to do that?

What I missed? @adamcin I am blocked. Please help

**Comment by pun-ky** [comment]
ok, instead of Docker I decided to build by my own OakPAL from tag 1.5.1 and use CLI jars (it would be nice to have dist ZIP exposed somewhere, e.g on "Releases" tab on GitHub), then by using debugger I spotted that:

1. my jar was in use, but I forgot to remove oakpal cache dir so that I shouldn't see my changes; maybe calculating checksum here will allow to work with snapshot version of oakpal opear file (dev mode)
2. plan name passed via CLI must end with extension :) it would be nice to be documented
3. no way to provide plan externally if not provided in Opear file; I understand complete opear related resources encapsulation but for mixed case... getting ACS Commons Opear File and allowing to choose which checklists to be used, or just correcting single option like skipping checking vault install hooks to be used, could be nice 

in my case current option will be to extract ACS AEM Commons JAR and use Opear from reading from directory..

are my assumptions correct? ;)

**Comment by pun-ky** [comment]
fyi @adamcin finally decided to integrate with OakPal by using core as dependency in a way that I am unpacking ACS AEM Commons OAKPal checks, then adding my custom project specific files like 'plan.json';

then my plugin https://github.com/Cognifide/gradle-aem-plugin is using `OpearFile.fromDirectory` and then `OakpalPlan.fromJson(planFile.takeIf { it.exists() }?.toURI()?.toURL() ?: opearFile.defaultPlan )` to be able to use plan unspecified in manifest file. This works nicely and meets my criteria.

Hope so used OakPAL Core API / behavior will remain available in future versions of OakPAL.

https://github.com/Cognifide/gradle-aem-plugin/pull/487/files#diff-1b8b0d2bc3c7d74e3a6c0f95937b9c66R78-R120

Greetings, Krystian :)

**Comment by adamcin** [comment]
@pun-ky Very cool! I am planning on making some largish changes to the API in version 2.0.0 for various reasons, but I using the bnd baseline plugin to ensure that I follow SemVer in my release artifacts according to the exported packages in the core bundle manifest. I do promise to keep downstream tool integrations in mind as I make changes to the oakpal API, and I will follow up with you if I expect breaking changes to affect your integration in the gradle-aem-plugin.

**Comment by pun-ky** [comment]
Almost released ;) https://github.com/Cognifide/gradle-aem-plugin/pull/491
thank you very much!

**Comment by pun-ky** [comment]
released, 
https://github.com/Cognifide/gradle-aem-plugin/releases/tag/8.1.0

**Comment by adamcin** [comment]
@pun-ky Awesome!
