### ISSUE TITLE
Allow to use plan from outside Opear file

### ISSUE THREAD

**Issue by pun-ky** [adamcin/oakpal#39]
https://mvnrepository.com/artifact/com.adobe.acs/acs-aem-commons-oakpal-checks/4.3.4

For example, this artifact has no plans defined. 
I'd like to use checklist for AEM  6.5 defined in this Opear file and set skipping Vault install hooks checking.

As of right now, when using `-f` parameter in CLI there is no way to provide plan from outside Opear file.

How such situation should be addressed? Is rebuilding Opear file really needed? I am afraid requiring setting up project for rebuilding this opear file could be too heavy and sometimes could discourage from using OakPAL.

**Comment by adamcin** [comment]
Thanks for the request, @pun-ky . I have actually been waiting to define a feature for generic plan overrides in the CLI until I collected enough use cases to flesh out the requirements for it. I'll add this one to the list.

In the meantime, I think I can safely add a `--no-hooks` switch to the CLI to override the plan's installHook policies with SKIP.

**Comment by pun-ky** [comment]
sounds great, cool, thanks ;)
