### ISSUE TITLE
Is it intentional that a ResourceBundle properties file is required now?

### ISSUE THREAD

**Issue by justinedelson** [adamcin/oakpal#59]
While upgrading from 1.4.1 to 2.1.0, I noticed that for any custom check, violations are not reporting unless there's a .properties file used for the ResourceBundle. Is this intentional?

I also might be doing something wrong of course :)

**Comment by adamcin** [comment]
Just noticed this issue, sorry. Are you overriding the getResourceBundleName() method to return null? In 2.1.0, I added the following to the ViolationReporter interface to drive the localization support:
```java

/**
 * Base interface for violation reporters.
 */
@ConsumerType
public interface ViolationReporter {

    /**
     * Get the resource bundle base name for loading the default resource bundle for this violation reporter. Returns
     * {@code getClass().getName()} by default. If this method is overridden to return null, the oakpal framework will
     * not attempt to load a parent resource bundle specific to this violation reporter when creating a resource bundle
     * during initialization.
     *
     * @return the resource bundle base name
     */
    @Nullable
    default String getResourceBundleBaseName() {
        return getClass().getName();
    }
```

**Comment by adamcin** [comment]
I must have intended to provide a default empty resource bundle at some point. I'll add it to the next release.
