### ISSUE TITLE
Provide baselines of node types and content classifications for major AEM versions in dedicated artifacts

### ISSUE THREAD

**Issue by kwin** [adamcin/oakpal#9]
Currently some initial config needs to be provided via manually maintained files (e.g. nodetypes via long CND files or forcedRoots for content classification checks, https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/88a9bec43adc3f39516e500a55e3d46e315739b6/oakpal-checks/src/main/resources/OAKPAL-INF/checklist/acs-internal.json#L62). 

It would be nice to provide

a) Maven goals to automatically retrieve/generate those two metadata files from running AEM instances
b) Pushing those metadata as dedicated artifacts to Maven Central so that one can easily upgrade to a newer base line

**Comment by adamcin** [comment]
In 1.3.0-RC2, I have added a feature called Webster to the oakpal framework, with the primary interface being an `oakpal:webster` maven mojo that is executed in a module directory, but not as part of the normal build lifecycle. Given a `webster.segmentStore` parameter that references an absolute path to a local oak repository's `segmentstore` directory, it uses a read-only CompositeNodeStore mount to construct a temporary JCR repository that imports the namespaces, privileges, and nodetypes from the source repository, and that at least exposes all of the content to query-by-traversal, if not by index. The plugin descriptor in the pom must specify one or more websterTargets in the configuration to define the path and type of file to be generated. Generally speaking, filevault-package modules will specify `nodetypes` and `privileges` targets, where as checklist jar modules will specify `checklist` targets. Here are some important features:
1. Package nodetypes.cnd and privileges.xml are generated to automatically include only those definitions that are referenced by .content.xml and *.cnd files in the filevault archive root. Very little configuration appears to be needed for maintaining these files at this point, so I am willing to conclude that for anyone other than Adobe to publish authoritative artifacts for these files would likely be overkill, and may introduce more issues by exporting more definitions than necessary. 
2. I have added a `net.adamcin.oakpal.core.JsonCnd`-managed structure with the root-level key, `jcrNodetypes` to the checklist json format to replace the now deprecated `cndNames` key. Combined with the existing `jcrNamespaces` list of prefix-to-uri mappings, this allows the JCR dependencies in a checklist to be managed by webster in a canonical, self-contained form, with the goal of making git diffs as readable as possible, and reducing the impact of drifting external dependencies.
